// Каталог инструментов MBOX — один на прод-сервер и dev-API (раньше было две копии, и они разошлись:
// в одной был «Сформировать фид», в другой — Browserbase). Правится только здесь.
export const TOOL_CATALOG = [
  {
    id: "tour-feed",
    name: "Сформировать фид",
    kind: "фид туров",
    group: "Данные и фиды",
    status: "готов локально",
    path: "C:\\Users\\a.nikolyuk\\Desktop\\Фиды",
    icon: "/assets/icons/project/sources.png",
    summary: "Собирает единый YML/XML-фид из файлов туров: сначала источники с префиксом 1, затем источники с префиксом 2 без повторяющихся ID.",
    capabilities: ["YML/XML", "категории из файлов", "приоритет источников", "удаление дублей"],
    commands: [
      { label: "Сформировать фид", command: "python merge_feeds.py \"01.06\"", runnable: true },
      { label: "Открыть папку", command: "explorer .", runnable: true },
    ],
  },
  {
    id: "obscura",
    name: "Obscura",
    kind: "браузер без окна",
    group: "SEO Wizard",
    status: "локально подключается",
    path: "C:\\Users\\a.nikolyuk\\Desktop\\Mbox\\obscura",
    repo: "https://github.com/h4ckf0r0day/obscura",
    docs: "https://docs.obscura.sh",
    icon: "/assets/icons/tools/obscura.png",
    summary: "Лёгкий браузерный движок для агентной автоматизации: загрузка страниц, stealth, CDP, скриншоты, PDF и MCP без запуска Chromium.",
    capabilities: ["web extraction", "screenshots", "PDF export", "CDP", "Playwright/Puppeteer", "MCP browser"],
    commands: [
      { label: "Сборка с render", command: "cargo build --release -p obscura-cli --bins --features render", env: { CARGO_INCREMENTAL: "0", CARGO_BUILD_JOBS: "2" }, runnable: true },
      { label: "Сервер CDP", command: "target\\release\\obscura.exe serve --port 9222", runnable: true, long_running: true },
      { label: "MCP stdio", command: "target\\release\\obscura.exe mcp", runnable: false },
      { label: "MCP HTTP", command: "target\\release\\obscura.exe mcp --http --port 3000", runnable: true, long_running: true },
    ],
  },
  {
    id: "figma",
    name: "Figma MCP",
    kind: "дизайн-контекст",
    group: "Дизайн",
    status: "нужна авторизация Figma",
    path: "C:\\Users\\a.nikolyuk\\Desktop\\Mbox",
    repo: "https://www.figma.com/mcp-catalog/",
    docs: "https://developers.figma.com/docs/figma-mcp-server/",
    icon: "/assets/icons/tools/figma.png",
    summary: "Официальный MCP Figma: читает дизайн-контекст, компоненты, переменные и Dev Mode данные; remote MCP требует авторизации, desktop MCP включается в Figma Desktop.",
    capabilities: ["design context", "components", "variables", "Dev Mode", "write to canvas"],
    commands: [
      { label: "Открыть Figma", command: "start \"\" \"figma://\"", runnable: true },
      { label: "Проверить desktop MCP", command: "powershell -NoProfile -Command \"try { (Invoke-WebRequest -UseBasicParsing http://127.0.0.1:3845/mcp -TimeoutSec 3).StatusCode } catch { $_.Exception.Message }\"", runnable: true },
      { label: "Codex remote MCP", command: "codex mcp add figma --url https://mcp.figma.com/mcp", runnable: true },
      { label: "Claude desktop MCP", command: "claude mcp add --transport http figma-desktop http://127.0.0.1:3845/mcp", runnable: true },
    ],
  },
  {
    id: "playwright-mcp",
    name: "Playwright MCP",
    kind: "автоматизация браузера",
    group: "Браузер и автоматизация",
    status: "установлен npm",
    path: "C:\\Users\\a.nikolyuk\\Desktop\\Mbox\\memora\\memora-graph",
    repo: "https://github.com/microsoft/playwright-mcp",
    docs: "https://playwright.dev/docs/getting-started-mcp",
    icon: "/assets/icons/tools/playwright.png",
    summary: "Официальный Playwright MCP для кликов, форм, снимков accessibility tree, скриншотов и browser QA. Настроен на системный Chrome, чтобы не ждать отдельный Chromium.",
    capabilities: ["clicks", "forms", "accessibility snapshots", "screenshots", "PDF", "local QA"],
    commands: [
      { label: "MCP HTTP", command: "npx @playwright/mcp --browser chrome --host 127.0.0.1 --port 9310 --caps vision,pdf", runnable: true, long_running: true },
      { label: "MCP stdio", command: "npx @playwright/mcp --browser chrome --caps vision,pdf", runnable: false },
      { label: "Установить Chromium", command: "npx playwright install chromium", env: { PLAYWRIGHT_DOWNLOAD_CONNECTION_TIMEOUT: "120000" }, runnable: true },
    ],
  },
  {
    id: "chrome-devtools-mcp",
    name: "Chrome DevTools MCP",
    kind: "отладка браузера",
    group: "Браузер и автоматизация",
    status: "установлен npm",
    path: "C:\\Users\\a.nikolyuk\\Desktop\\Mbox\\memora\\memora-graph",
    repo: "https://github.com/ChromeDevTools/chrome-devtools-mcp",
    docs: "https://developer.chrome.com/docs/devtools/agents/get-started",
    icon: "/assets/icons/tools/chrome-devtools.png",
    summary: "Официальный Chrome DevTools MCP для console/network/performance/DOM аудита и проверки живого Chrome из агента.",
    capabilities: ["console", "network", "performance", "DOM", "screenshots", "debugging"],
    commands: [
      { label: "MCP stable Chrome", command: "npx chrome-devtools-mcp --channel stable --viewport 1440x900", runnable: true, long_running: true },
      { label: "MCP slim", command: "npx chrome-devtools-mcp --channel stable --slim --viewport 1440x900", runnable: true, long_running: true },
      { label: "Chrome debug 9222", command: "\"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\" --remote-debugging-port=9222 --user-data-dir=\"%TEMP%\\mbox-chrome-debug\"", runnable: true, long_running: true },
      { label: "Подключиться к 9222", command: "npx chrome-devtools-mcp --browserUrl http://127.0.0.1:9222", runnable: true, long_running: true },
    ],
  },
  {
    id: "browserbase-stagehand",
    name: "Browserbase + Stagehand",
    kind: "облачный браузер",
    group: "Браузер и автоматизация",
    status: "пакеты установлены, нужны ключи",
    path: "C:\\Users\\a.nikolyuk\\Desktop\\Mbox\\memora\\memora-graph",
    repo: "https://github.com/browserbase/mcp-server-browserbase",
    docs: "https://docs.browserbase.com/",
    icon: "/assets/icons/tools/browserbase.png",
    summary: "Облачный браузерный MCP на Browserbase со Stagehand для долгих web-сценариев, извлечения данных и сессий с прокси. Требует BROWSERBASE_API_KEY и BROWSERBASE_PROJECT_ID.",
    capabilities: ["cloud sessions", "Stagehand act/extract/observe", "proxies", "stealth", "long-running browsing"],
    commands: [
      { label: "MCP HTTP", command: "npx @browserbasehq/mcp --browserbaseApiKey %BROWSERBASE_API_KEY% --browserbaseProjectId %BROWSERBASE_PROJECT_ID% --host 127.0.0.1 --port 9320 --browserWidth 1440 --browserHeight 900", runnable: true, long_running: true },
      { label: "Stagehand check", command: "node -e \"import('@browserbasehq/stagehand').then(() => console.log('Stagehand OK'))\"", runnable: true },
    ],
  },
  // SEO Wizard: четыре входа в общий мастер SEO. Карточки открывают один рабочий документ с настройками и пакетом.
  {
    id: "wordstat-api",
    name: "Wordstat API",
    kind: "SEO · спрос",
    group: "SEO Wizard",
    status: "подключён к SEO Wizard",
    icon: "/assets/icons/project/sources.png",
    summary: "Частотность запросов Яндекса: семантика, сезонность и регионы спроса для подбора ключей.",
    capabilities: ["частотность", "сезонность", "регионы", "похожие запросы"],
    commands: [],
  },
  {
    id: "topvisor-api",
    name: "Topvisor API",
    kind: "SEO · позиции",
    group: "SEO Wizard",
    status: "подключён к SEO Wizard",
    icon: "/assets/icons/project/sources.png",
    summary: "Позиции сайта в поиске по проектам Topvisor: динамика, видимость, сравнение с конкурентами.",
    capabilities: ["позиции", "видимость", "конкуренты", "кластеризация"],
    commands: [],
  },
  {
    id: "metrica-api",
    name: "Metrica API",
    kind: "SEO · трафик",
    group: "SEO Wizard",
    status: "подключён к SEO Wizard",
    icon: "/assets/icons/project/sources.png",
    summary: "Яндекс Метрика: поисковый трафик, поведение и конверсии по страницам и запросам.",
    capabilities: ["поисковый трафик", "поведение", "цели", "страницы входа"],
    commands: [],
  },
  {
    id: "webmaster-api",
    name: "Webmaster API",
    kind: "SEO · индексация",
    group: "SEO Wizard",
    status: "подключён к SEO Wizard",
    icon: "/assets/icons/project/sources.png",
    summary: "Яндекс Вебмастер: индексация, запросы с показами и кликами, ошибки и диагностика сайта.",
    capabilities: ["индексация", "поисковые запросы", "диагностика", "sitemap"],
    commands: [],
  },
];
